# -*- coding: utf-8 -*-
"""12question.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1nF6J8Z4fcj8kW-XWfkUcjOUQOswH5HZq
"""

import numpy as np

my_array = np.array([[1, 2, 3], [4, 5, 6]])

print("Type of array:", type(my_array))

print("Axes of array:", my_array.ndim)

print("Shape of array:", my_array.shape)

print("Type of elements in array:", my_array.dtype)

